name: Run R tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-r-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install testthat
      run: |
        Rscript -e "if (!requireNamespace('testthat', quietly = TRUE)) install.packages('testthat')"

    - name: Run tests
      run: |
        Rscript -e "testthat::test_dir('tests')"
